version: '3.8'

services:

  backend:
    build:
      context: ./backend
    ports:
      - "9000:8000" 
    container_name: fruits-backend

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:5173"
    container_name: fruits-frontend
    stdin_open: true
    tty: true
    depends_on:
      - backend
